language: node_js
node_js:
  - "12.6.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install
  - echo $FIREBASE_CONFIG > src/config.js

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

