language: node_js
node_js:
  - "8.1.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change
